export const REDUCER_NAME = 'navigation'

export const ACTIONS = {
    INIT_DEFAULT_FOCUS: `${REDUCER_NAME}/INIT_DEFAULT_FOCUS`,
    NAVIGATE_BY_KEYPRESS: `${REDUCER_NAME}/NAVIGATE_BY_KEYPRESS`,
    STORE_MENU_ELEMENTS: `${REDUCER_NAME}/STORE_MENU_ELEMENTS`,
    STORE_CONTENT_ELEMENTS: `${REDUCER_NAME}/STORE_CONTENT_ELEMENTS`,
    STORE_CURRENT_FOCUS: `${REDUCER_NAME}/STORE_CURRENT_FOCUS`,
    STORE_LAST_FOCUS_OF_COMPONENT: `${REDUCER_NAME}/STORE_LAST_FOCUS_OF_COMPONENT`,
    FOCUS_CHANGED: `${REDUCER_NAME}/FOCUS_CHANGED`,
    STORE_CURRENT_CONTENT_OFFSET: `${REDUCER_NAME}/STORE_CURRENT_CONTENT_OFFSET`
}
